nguage: java

jdk: oraclejdk8

script:
          - mvn package
          - mvn sonar:sonar \
             -Dsonar.projectKey=ghaniturismo_TP_bootiful \
               -Dsonar.organization=ghaniturismo-github \
                 -Dsonar.host.url=https://sonarcloud.io \
                   -Dsonar.login=ae7b83eb7fc46aa48706dc29649d7f593e46a397
